### ISSUE TITLE
ObjectBenderEditor leaks callbacks

### ISSUE THREAD

**Issue by Kronoxis** [Dreamteck/splines#11]
See [Discord thread](https://discord.com/channels/375397264828530688/1161057200106651669)

The `ObjectBenderEditor` does not call its `base.OnDestroy` method, which causes it to leak the `DuringSceneGUI` method to the SceneView, and in turn errors when the ObjectBender gets destroyed, as well as causing performance issues over time as the GUI gets called many times per SceneView update.

Adding the following line fixes the issues:
https://github.com/Dreamteck/splines/blob/d9097728db1181f11619c53eabce2bbc26389d01/Assets/Dreamteck/Splines/Editor/Components/ObjectBenderEditor.cs#L342-L343
```CSharp
+            base.OnDestroy();
```
https://github.com/Dreamteck/splines/blob/d9097728db1181f11619c53eabce2bbc26389d01/Assets/Dreamteck/Splines/Editor/Components/ObjectBenderEditor.cs#L344-L354

**Comment by GMihalkow** [comment]
@Kronoxis thank you for the fix
